do $$
begin
  if (select count(*) from public.reviews) < 10 then
    insert into public.reviews (product_slug,name,stars,text,color,verified,fecha,position) values
    ('airpods-max','Ignacio T.',5,'La calidad de sonido es otro nivel. Muy cómodos para usar horas seguidas.','Midnight',false,'2026-09-12',1),
    ('airpods-max','Romina F.',5,'La fijación magnética es precisa, calza de una sin buscar el punto.','Starlight',false,'2026-08-24',2),
    ('airpods-max','Marcelo D.',5,'Terminación premium de verdad. Se siente el metal, no plástico pintado.','Purple',false,'2026-08-06',3),
    ('airpods-max','Javiera S.',5,'Los colores se ven tal cual la foto. Quedé encantada.','Midnight',false,'2026-07-18',4),
    ('airpods-max','Álex M.',4,'Muy buenos 👌','Orange',false,'2026-06-27',5),
    ('airpods-max','Tamara C.',4,'Suenan excelente.','Starlight',false,'2026-06-08',6),
    ('airpods-max','Luis P.',4,'👍👍','Blue',false,'2026-05-19',7),
    ('airpods-max','Catalina V.',4,'Buen producto, llegó bien protegido.','Midnight',false,'2026-04-30',8),
    ('buds4-pro','Camila R.',5,'El sonido es potente y la cancelación de ruido funciona muy bien en la micro.','Negro',false,'2026-09-19',1),
    ('buds4-pro','Diego M.',5,'Livianos, casi no se sienten en la oreja. Los uso todo el día trabajando.','Gris',false,'2026-09-04',2),
    ('buds4-pro','Fernanda P.',5,'El rosa se ve precioso en persona, igual que en la foto. Muy contenta.','Rosa',false,'2026-08-21',3),
    ('buds4-pro','Sebastián L.',5,'Se conectan al Galaxy al instante. La batería me dura toda la jornada.','Negro',false,'2026-08-07',4),
    ('buds4-pro','Antonia V.',5,'El estuche carga rápido y entra en cualquier bolsillo.','Negro',false,'2026-07-23',5),
    ('buds4-pro','Matías C.',5,'Compré ocho para revender y salieron todos parejos. Buen producto.','Gris',false,'2026-07-09',6),
    ('buds4-pro','Valeria S.',4,'Muy buenos 👌','Rosa',false,'2026-06-25',7),
    ('buds4-pro','Joaquín A.',4,'Buen sonido y cómodos.','Negro',false,'2026-06-10',8),
    ('buds4-pro','Paulina T.',4,'Cumplen de sobra 👍','Gris',false,'2026-05-26',9),
    ('buds4-pro','Nicolás B.',4,'Llegaron rápido y bien embalados ✅','Negro',false,'2026-05-08',10),
    ('buds2-pro','Constanza F.',5,'Muy cómodos y el sonido se escucha limpio. Los uso todos los días para ir al trabajo.','',false,'2026-09-16',1),
    ('buds2-pro','Ignacio R.',5,'Chiquitos y livianos, casi no se sienten. La cancelación de ruido cumple de sobra.','',false,'2026-08-29',2),
    ('buds2-pro','Martina D.',5,'Se conectan solos al teléfono apenas abro el estuche. Muy práctico.','',false,'2026-08-11',3),
    ('buds2-pro','Álvaro S.',5,'Buena batería, me duran toda la jornada sin cargarlos.','',false,'2026-07-24',4),
    ('buds2-pro','Josefa M.',4,'Muy buenos 👌','',false,'2026-07-02',5),
    ('buds2-pro','Cristóbal N.',4,'Buen producto y llegó rápido ✅','',false,'2026-06-14',6),
    ('buds2-pro','Daniela A.',4,'Cumplen muy bien por lo que cuestan 👍','',false,'2026-05-21',7),
    ('iphone-15-128','Rodrigo V.',5,'Llegó sellado y con todo original. La cámara es una maravilla.','',false,'2026-09-21',1),
    ('iphone-15-128','Camila B.',5,'El USB-C se agradece, cargo el teléfono con el mismo cable del notebook.','',false,'2026-09-02',2),
    ('iphone-15-128','Felipe O.',5,'Me asesoraron bien sobre el almacenamiento. Muy buena atención.','',false,'2026-08-13',3),
    ('iphone-15-128','Antonia L.',5,'La pantalla se ve increíble incluso con sol directo.','',false,'2026-07-26',4),
    ('iphone-15-128','Matías G.',5,'Segundo teléfono que compro acá. Producto impecable.','',false,'2026-06-30',5),
    ('iphone-15-128','Valeria C.',4,'Excelente teléfono 🔥','',false,'2026-06-05',6),
    ('iphone-15-128','Tomás R.',5,'Llegó en tres días a Rancagua, bien embalado y sin un rayón.','',false,'2026-05-14',7),
    ('iphone-16-128','Sebastián P.',5,'El chip A18 se nota, todo vuela. Muy buena compra.','',false,'2026-09-23',1),
    ('iphone-16-128','Francisca T.',5,'El botón de cámara es súper cómodo para tomar fotos rápido.','',false,'2026-09-01',2),
    ('iphone-16-128','Nicolás A.',5,'Llegó en dos días, sellado y con su número de serie válido.','',false,'2026-08-08',3),
    ('iphone-16-128','Paula H.',4,'La batería me dura todo el día con uso pesado 👍','',false,'2026-07-15',4),
    ('iphone-16-128','Ignacio D.',5,'Llegó sellado y con todo original. La cámara saca unas fotos increíbles.','',false,'2026-06-22',5),
    ('iphone-16-128','Catalina M.',5,'Me asesoraron por WhatsApp antes de decidir. Muy buena atención.','',false,'2026-05-30',6),
    ('s26-plus-256','Tomás M.',5,'La pantalla es enorme y se ve espectacular. Muy contento.','',false,'2026-09-18',1),
    ('s26-plus-256','Javiera C.',5,'Los 256 GB me sobran para fotos y videos. Carga muy rápido.','',false,'2026-08-22',2),
    ('s26-plus-256','Benjamín S.',5,'Llegó sellado y con todo lo que decía la descripción.','',false,'2026-07-19',3),
    ('s26-plus-256','Romina A.',4,'Muy buen teléfono 👍','',false,'2026-09-08',4),
    ('s26-plus-256','Cristián V.',5,'Viniendo de un S21, el salto se nota en todo. La cámara de noche es otra cosa.','',false,'2026-08-05',5),
    ('s26-plus-256','Daniela E.',5,'Me respondieron todas las dudas por WhatsApp antes de comprar. Buena atención.','',false,'2026-07-28',6),
    ('s26-plus-256','Matías Z.',5,'La batería me dura el día completo con uso pesado. Muy contento.','',false,'2026-07-04',7),
    ('s26-plus-256','Fernanda I.',5,'Llegó en tres días a Valparaíso, bien embalado y con todo original.','',false,'2026-06-16',8),
    ('s26-plus-256','Gonzalo P.',4,'Excelente equipo 🔥','',false,'2026-05-30',9),
    ('s26-plus-256','Antonia B.',4,'Muy buen producto ✅','',false,'2026-05-12',10),
    ('s26-plus-256','Rodrigo Q.',5,'El S Pen no viene, pero el equipo es un fierro. Lo recomiendo.','',false,'2026-04-24',11),
    ('s26-plus-256','Camila U.',4,'Cumple todo lo que promete 👌','',false,'2026-04-06',12),
    ('s26-plus-256','Esteban W.',5,'Segundo Samsung que compro acá. Siempre producto original y bien embalado.','',false,'2026-03-18',13),
    ('s26-plus-256','Marcela D.',5,'La pantalla grande se agradece para ver series en el bus.','',false,'2026-03-02',14),
    ('s26-plus-256','Hugo T.',5,'Compré dos, uno para mí y otro para mi señora. Los dos perfectos.','',false,'2026-02-14',15),
    ('s26-plus-256','Paulina R.',4,'Buen equipo por el precio 👍','',false,'2026-01-27',16),
    ('s26-plus-256','Álvaro N.',5,'Atención rápida y el envío llegó cuando dijeron.','',false,'2026-01-09',17),
    ('s26-plus-256','Josefina B.',5,'Muy buena cámara, las fotos salen nítidas incluso con poca luz.','',false,'2025-12-18',18),
    ('s26-plus-256','Renato C.',4,'Excelente 🔥','',false,'2025-11-30',19),
    ('cargador-samsung-45w','Marcela G.',5,'Carga el Galaxy completo en menos de una hora. Impresionante.','',false,'2026-09-06',1),
    ('cargador-samsung-45w','Cristián P.',4,'Carga rápido 🔥','',false,'2026-08-20',2),
    ('cargador-samsung-45w','Daniela V.',4,'Buen producto.','',false,'2026-08-02',3),
    ('cargador-samsung-45w','Rodrigo S.',4,'Sirve también para mi notebook. Recomendado 👍','',false,'2026-07-15',4),
    ('cargador-samsung-45w','Francisca A.',4,'Todo bien ✅','',false,'2026-06-28',5),
    ('cargador-samsung-45w','Nelson M.',4,'Trae el cable incluido. Cumple.','',false,'2026-06-11',6),
    ('cargador-samsung-45w','Catalina R.',4,'Funciona con toda la línea Galaxy de la casa.','',false,'2026-05-22',7),
    ('cargador-samsung-45w','Benjamín T.',4,'Muy buen cargador.','',false,'2026-05-04',8),
    ('cargador-samsung-45w','Susana C.',4,'Buen precio para esta potencia 👌','',false,'2026-04-09',9),
    ('bateria-magsafe','Francisca L.',5,'Se pega firme al iPhone y carga sin cables. Justo lo que buscaba para viajar.','',false,'2026-09-17',1),
    ('bateria-magsafe','Roberto S.',5,'Cabe en el bolsillo con el teléfono pegado. Muy práctica para el día.','',false,'2026-09-02',2),
    ('bateria-magsafe','Daniela T.',5,'Me carga el iPhone de 20 a 80 por ciento sin enchufarlo a nada. Perfecta.','',false,'2026-08-18',3),
    ('bateria-magsafe','Paz M.',5,'El imán es fuerte, no se suelta ni caminando rápido.','',false,'2026-08-04',4),
    ('bateria-magsafe','Hernán V.',5,'Compré doce para revender y salieron todas parejas. Producto sólido.','',false,'2026-07-22',5),
    ('bateria-magsafe','Melissa A.',5,'La uso en viajes largos en bus. Me salva cuando no hay enchufe.','',false,'2026-07-08',6),
    ('bateria-magsafe','Gustavo P.',5,'Llegó con el cable incluido, como decía la descripción. Cumple lo que dice.','',false,'2026-06-23',7),
    ('bateria-magsafe','Cristián O.',4,'Funciona muy bien 👍','',false,'2026-06-05',8),
    ('bateria-magsafe','Antonia R.',4,'Buena y compacta.','',false,'2026-05-20',9),
    ('bateria-magsafe','Carla B.',4,'Buen producto ✅','',false,'2026-05-02',10),
    ('bateria-magsafe','Eduardo L.',4,'Liviana y bien terminada 💯','',false,'2026-04-14',11),
    ('cargador-lightning','Paula N.',5,'Funciona perfecto y el cable se siente firme. Cumple lo que promete.','',false,'2026-09-09',1),
    ('cargador-lightning','Víctor A.',5,'Carga igual de rápido que el original de Apple, a un tercio del precio.','',false,'2026-08-26',2),
    ('cargador-lightning','Mónica R.',4,'Compré veinte para el local y salió un lote parejo 👍','',false,'2026-08-12',3),
    ('cargador-lightning','Felipe C.',4,'Buen producto.','',false,'2026-07-29',4),
    ('cargador-lightning','Ximena S.',4,'Trae el adaptador incluido. Todo bien ✅','',false,'2026-07-14',5),
    ('cargador-lightning','Raúl M.',4,'Lo uso con el iPad y el iPhone, funciona en los dos.','',false,'2026-06-30',6),
    ('cargador-lightning','Karen L.',4,'Muy práctico 👌','',false,'2026-06-13',7),
    ('cargador-lightning','Daniela B.',4,'Cumple 👍','',false,'2026-05-28',8),
    ('cargador-lightning','Sergio V.',4,'Llegó al día siguiente. Excelente.','',false,'2026-05-11',9),
    ('cargador-lightning','Óscar D.',4,'Buen precio y hace lo suyo.','',false,'2026-04-26',10),
    ('cargador-lightning','Bernardita P.',4,'Segunda compra del mismo 🔥','',false,'2026-04-08',11),
    ('cargador-lightning','Jorge F.',4,'Buena atención y el cargador cumple.','',false,'2026-03-22',12),
    ('airpods-3','Susana L.',5,'Cómodos para todo el día. No aprietan como los que traen gomita.','',false,'2026-09-14',1),
    ('airpods-3','Ariel P.',5,'La carga MagSafe es práctica, los dejo en la misma base del teléfono.','',false,'2026-08-31',2),
    ('airpods-3','Priscila M.',5,'Resisten el sudor sin problema. Los uso corriendo tres veces por semana.','',false,'2026-08-18',3),
    ('airpods-3','Damián R.',5,'Muy buena opción si no querés gastar en los Pro. El audio espacial ya viene incluido.','',false,'2026-08-04',4),
    ('airpods-3','Elisa C.',4,'Pedí ocho unidades y se venden solos 🔥','',false,'2026-07-21',5),
    ('airpods-3','Verónica D.',4,'El micrófono se escucha claro en reuniones.','',false,'2026-07-06',6),
    ('airpods-3','Iván B.',4,'Llegaron bien embalados 👍','',false,'2026-06-20',7),
    ('airpods-3','Natalia G.',4,'Se los compré a mi mamá y le encantaron porque son livianos.','',false,'2026-06-04',8),
    ('airpods-3','Esteban Q.',4,'Buena batería 👌','',false,'2026-05-18',9),
    ('airpods-3','Loreto F.',4,'Atención rápida y clara.','',false,'2026-05-03',10),
    ('airpods-3','Andrés K.',4,'Tercera vez que compro acá ✅','',false,'2026-04-17',11),
    ('airpods-3','Matías V.',4,'Buen producto.','',false,'2026-04-01',12),
    ('airpods-3','Rodolfo A.',4,'Buen sonido y livianos 👍','',false,'2026-03-14',13),
    ('apple-watch-serie-10','Daniela M.',5,'Muy lindo el reloj. Se ve tal cual en las fotos, es cómodo y tiene varias funciones. La configuración fue sencilla y funciona súper bien.','',false,'2026-09-18',1),
    ('apple-watch-serie-10','Antonia G.',5,'Todo perfecto, gracias. Llegó en dos días y bien embalado.','',false,'2026-09-05',2),
    ('apple-watch-serie-10','Matías O.',5,'Es notoriamente más delgado que el Serie 9. Casi no se siente puesto.','',false,'2026-08-23',3),
    ('apple-watch-serie-10','Francisca D.',5,'La pantalla grande se agradece para leer mensajes sin sacar el teléfono.','',false,'2026-08-10',4),
    ('apple-watch-serie-10','Valeria N.',5,'La carga rápida es real, en media hora ya estaba en 80 por ciento.','',false,'2026-07-27',5),
    ('apple-watch-serie-10','Diego T.',5,'Pedí cinco unidades y llegaron todas en su caja sellada. Cero problemas.','',false,'2026-07-13',6),
    ('apple-watch-serie-10','Macarena Q.',5,'El monitoreo del sueño me sirvió mucho. Datos claros y fáciles de leer en la app.','',false,'2026-06-29',7),
    ('apple-watch-serie-10','Álvaro J.',5,'Consulté por WhatsApp antes de comprar y me contestaron al rato. Buena atención.','',false,'2026-06-14',8),
    ('apple-watch-serie-10','Gonzalo Y.',5,'Lo compré para el trabajo, contesto llamadas sin sacar el celular del bolsillo.','',false,'2026-05-31',9),
    ('apple-watch-serie-10','Camila Ñ.',5,'Segunda unidad que pido, la primera se la quedó mi hermana. Producto tal cual la descripción.','',false,'2026-05-16',10),
    ('apple-watch-serie-10','Isidora K.',5,'Llegó a Concepción en el plazo que me dijeron. La app está en español y se entiende todo.','',false,'2026-04-29',11),
    ('apple-watch-serie-10','Sebastián I.',4,'Muy buen reloj 🔥','',false,'2026-04-12',12),
    ('apple-watch-serie-10','Bárbara U.',4,'Cumple todo lo que promete 👍','',false,'2026-03-28',13),
    ('apple-watch-serie-10','Renato W.',4,'Buena relación precio calidad.','',false,'2026-03-09',14),
    ('cargador-tipo-c','Cristóbal A.',5,'Carga rápido de verdad. Buen precio comparado con otras tiendas.','',false,'2026-09-08',1),
    ('cargador-tipo-c','Verónica M.',5,'Lo uso con el iPhone 15 y el MacBook Air. Sirve para los dos sin problema.','',false,'2026-08-27',2),
    ('cargador-tipo-c','Pedro S.',5,'Los 20W se notan, en media hora sube bastante la carga.','',false,'2026-08-15',3),
    ('cargador-tipo-c','Constanza D.',5,'Compré veinticinco y es el que más rota en mi tienda. Buen producto de entrada.','',false,'2026-08-02',4),
    ('cargador-tipo-c','Camila P.',5,'Trae todo listo para usar. Lo enchufé y funcionó al instante.','',false,'2026-07-20',5),
    ('cargador-tipo-c','Gonzalo A.',5,'Sirve también para el iPad Pro, que era lo que necesitaba.','',false,'2026-07-07',6),
    ('cargador-tipo-c','Josefina V.',4,'Llegó bien empaquetado 👍','',false,'2026-06-24',7),
    ('cargador-tipo-c','Matías L.',4,'Uno de los mejores precios que encontré.','',false,'2026-06-10',8),
    ('cargador-tipo-c','Nicolás R.',4,'Buen cargador ✅','',false,'2026-05-27',9),
    ('cargador-tipo-c','Andrea B.',4,'Cumple bien.','',false,'2026-05-13',10),
    ('cargador-tipo-c','Emilio N.',4,'Tres meses cargando a diario y sigue igual 💯','',false,'2026-04-28',11),
    ('cargador-tipo-c','Maite F.',4,'Me avisaron cuando llegó el stock. Anda perfecto.','',false,'2026-04-11',12),
    ('cargador-tipo-c','Hugo C.',4,'Carga bien 👌','',false,'2026-03-26',13),
    ('cargador-tipo-c','Paola G.',4,'Muy buena compra por el precio.','',false,'2026-03-08',14),
    ('cargador-tipo-c','Tomás E.',4,'Anda bien y no se calienta 👍','',false,'2026-02-19',15),
    ('apple-watch-ultra-3','Andrea C.',5,'Súper linda experiencia de compra. Me ayudaron a elegir correctamente todo. Feliz con mi compra.','Negro',false,'2026-09-15',1),
    ('apple-watch-ultra-3','Rodrigo M.',5,'El titanio se siente firme, nada de plástico. Lo uso para correr y el GPS marca bien las rutas.','Gris',false,'2026-09-03',2),
    ('apple-watch-ultra-3','Catalina B.',5,'La batería es lo mejor. Lo cargo dos veces por semana y listo. Vengo de un Serie 6 y el cambio se nota.','Negro',false,'2026-08-22',3),
    ('apple-watch-ultra-3','Felipe A.',5,'Llegó sellado y con todo lo que decía. La pantalla se ve perfecta incluso con sol directo.','Naranja',false,'2026-08-11',4),
    ('apple-watch-ultra-3','Nicolás P.',5,'Compré tres para revender y salieron todos iguales, sin detalles. Buen margen al por mayor.','Negro',false,'2026-07-31',5),
    ('apple-watch-ultra-3','Daniela S.',5,'Lo pedí un martes y llegó el jueves a Viña. Bien embalado, con doble burbuja.','Gris',false,'2026-07-19',6),
    ('apple-watch-ultra-3','Tomás L.',5,'La correa de titanio es cómoda. Nada de marcas en la muñeca después de todo el día.','Negro',false,'2026-07-08',7),
    ('apple-watch-ultra-3','Constanza R.',5,'Resiste el agua sin problema, lo usé en la piscina varias veces y sigue igual.','Naranja',false,'2026-06-26',8),
    ('apple-watch-ultra-3','Paulina E.',5,'Segunda compra acá. Responden rápido y cumplen los plazos que dicen.','Gris',false,'2026-06-13',9),
    ('apple-watch-ultra-3','Cristián H.',5,'La configuración fue directa, lo emparejé con el iPhone en dos minutos.','Negro',false,'2026-05-30',10),
    ('apple-watch-ultra-3','Marisol T.',5,'El botón de acción se puede configurar para el cronómetro. Muy útil entrenando.','Naranja',false,'2026-05-17',11),
    ('apple-watch-ultra-3','Pablo Ú.',5,'La sirena de emergencia se escucha fuerte de verdad. Lo llevo cuando salgo a cerro.','Negro',false,'2026-05-04',12),
    ('apple-watch-ultra-3','Elena R.',5,'Todo original, con su número de serie válido en la app de Apple. Sin sorpresas.','Gris',false,'2026-04-20',13),
    ('apple-watch-ultra-3','Camila Z.',5,'Se lo regalé a mi pareja y quedó feliz. Se ve mucho mejor en persona que en foto.','Negro',false,'2026-04-06',14),
    ('apple-watch-ultra-3','Josefa V.',4,'Muy bueno 🔥','Naranja',false,'2026-03-20',15),
    ('apple-watch-ultra-3','Ignacio F.',4,'Excelente reloj y muy completo 👍','Negro',false,'2026-03-02',16),
    ('airpods-4','Jorge R.',5,'Llegó rápido y bien envuelto. Muy buen sonido, se recomienda.','',false,'2026-09-19',1),
    ('airpods-4','Camila S.',5,'Los compré para el gimnasio y no se caen. La batería dura todo el día sin problema.','',false,'2026-09-07',2),
    ('airpods-4','Esteban D.',5,'El diseño nuevo calza mejor en la oreja que los de tercera. Se sienten más firmes.','',false,'2026-08-27',3),
    ('airpods-4','Rocío T.',5,'El audio adaptativo funciona bien en la micro, baja el ruido solo.','',false,'2026-08-16',4),
    ('airpods-4','Carolina H.',5,'Compré diez para revender y llegaron todos sellados. Buen precio por volumen.','',false,'2026-08-05',5),
    ('airpods-4','Mauricio L.',5,'Se conectan al iPhone al instante. Cero configuración, funcionó al abrir la caja.','',false,'2026-07-25',6),
    ('airpods-4','Belén A.',5,'Uso el estuche todo el día y el sonido de llamadas se escucha claro del otro lado.','',false,'2026-07-14',7),
    ('airpods-4','Franco P.',5,'Llegaron a Antofagasta en cuatro días. Buen seguimiento del envío.','',false,'2026-07-02',8),
    ('airpods-4','Cristóbal Z.',5,'Los tengo hace tres meses y siguen igual que el primer día. Buena compra.','',false,'2026-06-20',9),
    ('airpods-4','Amanda V.',5,'Me asesoraron bien para elegir entre estos y los Pro. Quedé contenta con la elección.','',false,'2026-06-07',10),
    ('airpods-4','Lorena Í.',5,'Se emparejan con el iPad y el Mac sin tocar nada. Muy cómodo para trabajar.','',false,'2026-05-25',11),
    ('airpods-4','Teresa O.',5,'Cumplen de sobra para el día a día. Los uso desde que me levanto.','',false,'2026-05-12',12),
    ('airpods-4','Pablo M.',4,'Muy buenos 👌','',false,'2026-04-29',13),
    ('airpods-4','Dominga C.',4,'Buen sonido y cómodos.','',false,'2026-04-15',14),
    ('airpods-4','Simón B.',4,'Recomendados 👍','',false,'2026-03-30',15),
    ('airpods-4','Julián W.',4,'Buenos audífonos ✅','',false,'2026-03-12',16),
    ('airpods-4','Marcos H.',4,'Muy buena relación precio calidad.','',false,'2026-02-24',17),
    ('airpods-pro-2','Alain P.',5,'Excelentes audífonos. Me encantaron. El sonido es increíble y tienen un bajo bien profundo.','',false,'2026-09-20',1),
    ('airpods-pro-2','Rosemarie P.',5,'Me encantaron. Se escuchan muy bien, la cancelación de ruido funciona tal como esperaba.','',false,'2026-09-10',2),
    ('airpods-pro-2','Sebastián O.',5,'Segunda compra en la tienda. Responden rápido las dudas por WhatsApp y el envío llegó antes de lo estimado.','',false,'2026-08-30',3),
    ('airpods-pro-2','Nicole F.',5,'La cancelación de ruido en el metro es otra cosa. Se apaga el mundo.','',false,'2026-08-20',4),
    ('airpods-pro-2','Héctor G.',5,'Los uso para trabajar ocho horas y no me molestan las orejas. Muy livianos.','',false,'2026-08-10',5),
    ('airpods-pro-2','Leonardo M.',5,'Compré quince para el local y todos originales, con número de serie válido.','',false,'2026-07-31',6),
    ('airpods-pro-2','Karla S.',5,'El modo transparencia es muy útil para andar en bicicleta y escuchar el tráfico.','',false,'2026-07-21',7),
    ('airpods-pro-2','Óscar T.',5,'Llegaron en 24 horas a Santiago centro. Increíble la rapidez.','',false,'2026-07-10',8),
    ('airpods-pro-2','Michelle A.',5,'El audio espacial en películas se siente envolvente de verdad, no es puro marketing.','',false,'2026-06-29',9),
    ('airpods-pro-2','Gabriela N.',5,'Es el producto que más vendo. Siempre hay stock cuando lo pido.','',false,'2026-06-18',10),
    ('airpods-pro-2','Nelson V.',5,'Buen precio, producto original y envío rápido. Nada más que pedir.','',false,'2026-06-06',11),
    ('airpods-pro-2','Fabiola R.',5,'Vienen tres tamaños de gomita. Con las medianas quedó perfecto y no se caen.','',false,'2026-05-24',12),
    ('airpods-pro-2','Arturo É.',5,'El estuche avisa la batería en el teléfono. Detalle chico que se agradece.','',false,'2026-05-11',13),
    ('airpods-pro-2','Ninoska B.',5,'Los pedí para regalo y llegaron a tiempo para el cumpleaños. Gracias por la rapidez.','',false,'2026-04-27',14),
    ('airpods-pro-2','Wilson D.',5,'El estuche con parlante para encontrarlos es una idea genial. Ya lo usé dos veces.','',false,'2026-04-13',15),
    ('airpods-pro-2','Solange R.',5,'Los mejores que he tenido. Los uso en avión y se nota muchísimo la diferencia.','',false,'2026-03-29',16),
    ('airpods-pro-2','Rubén C.',4,'Cumplen todo 🔥','',false,'2026-03-15',17),
    ('airpods-pro-2','Estefanía L.',4,'Suenan excelente 👍','',false,'2026-02-26',18);
  end if;
end $$;
